// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // CORREÇÃO: Aponta estritamente para a conexão direta (Porta 5432).
    // Bypassa o Pooler de conexões do Supabase em tempo de migração.
    url: process.env['DIRECT_URL'],
  },
});
